import {
  Volunteer,
  NGO,
  NormalUser,
  CommunityNeed,
  VolunteerTask,
  VolunteerApplication,
} from './types';

// Mock Volunteers
export const mockVolunteers: Volunteer[] = [
  {
    id: 'v1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '9876543210',
    role: 'volunteer',
    city: 'Mumbai',
    state: 'Maharashtra',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    createdAt: new Date('2024-01-15'),
    skills: ['Medical Training', 'First Aid', 'Community Health'],
    availability: 'Weekends',
    certificates: ['Red Cross First Aid', 'Health & Safety'],
    domains: ['Medical', 'Social Support'],
    tasksCompleted: 12,
    rating: 4.8,
    hoursContributed: 156,
  },
  {
    id: 'v2',
    name: 'Raj Kumar',
    email: 'raj@example.com',
    phone: '9876543211',
    role: 'volunteer',
    city: 'Delhi',
    state: 'Delhi',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=raj',
    createdAt: new Date('2024-02-20'),
    skills: ['Education', 'Tutoring', 'Programming'],
    availability: 'Evenings',
    certificates: ['Teaching Certification'],
    domains: ['Education', 'Infrastructure'],
    tasksCompleted: 8,
    rating: 4.6,
    hoursContributed: 120,
  },
  {
    id: 'v3',
    name: 'Ananya Desai',
    email: 'ananya@example.com',
    phone: '9876543212',
    role: 'volunteer',
    city: 'Bangalore',
    state: 'Karnataka',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ananya',
    createdAt: new Date('2024-03-10'),
    skills: ['Disaster Management', 'Logistics', 'Community Outreach'],
    availability: 'Full-time',
    certificates: ['Disaster Management', 'CERT Training'],
    domains: ['Disaster Relief', 'Environmental'],
    tasksCompleted: 15,
    rating: 4.9,
    hoursContributed: 280,
  },
  {
    id: 'v4',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    phone: '9876543213',
    role: 'volunteer',
    city: 'Chennai',
    state: 'Tamil Nadu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
    createdAt: new Date('2024-01-25'),
    skills: ['Food Distribution', 'Cooking', 'Sanitation'],
    availability: 'Weekdays',
    certificates: ['Food Safety', 'Hygiene Certification'],
    domains: ['Food', 'Sanitation'],
    tasksCompleted: 10,
    rating: 4.7,
    hoursContributed: 140,
  },
  {
    id: 'v5',
    name: 'Meera Patel',
    email: 'meera@example.com',
    phone: '9876543214',
    role: 'volunteer',
    city: 'Pune',
    state: 'Maharashtra',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meera',
    createdAt: new Date('2024-02-14'),
    skills: ['Environmental Conservation', 'Waste Management', 'Water Conservation'],
    availability: 'Flexible',
    certificates: ['Environmental Science'],
    domains: ['Environmental', 'Sanitation'],
    tasksCompleted: 7,
    rating: 4.5,
    hoursContributed: 95,
  },
];

// Mock NGOs
export const mockNGOs: NGO[] = [
  {
    id: 'ngo1',
    name: 'Health First Foundation',
    organizationName: 'Health First Foundation',
    email: 'contact@healthfirst.org',
    phone: '9123456789',
    role: 'ngo',
    city: 'Mumbai',
    state: 'Maharashtra',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=health',
    createdAt: new Date('2023-06-01'),
    description: 'Providing healthcare services and medical awareness to underserved communities',
    verificationStatus: 'Verified',
    socialHandles: {
      twitter: '@healthfirst',
      facebook: 'healthfirstfoundation',
      instagram: 'healthfirst_ngo',
    },
    domains: ['Medical', 'Social Support'],
    volunteersManaged: 24,
    tasksCreated: 18,
  },
  {
    id: 'ngo2',
    name: 'Education for All',
    organizationName: 'Education for All Initiative',
    email: 'team@eduforall.org',
    phone: '9123456790',
    role: 'ngo',
    city: 'Delhi',
    state: 'Delhi',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=education',
    createdAt: new Date('2023-07-15'),
    description: 'Making quality education accessible to every child',
    verificationStatus: 'Verified',
    socialHandles: {
      twitter: '@eduforall',
      facebook: 'educationforall',
      instagram: 'edu_for_all',
    },
    domains: ['Education', 'Social Support'],
    volunteersManaged: 35,
    tasksCreated: 22,
  },
  {
    id: 'ngo3',
    name: 'Disaster Relief Collective',
    organizationName: 'Disaster Relief Collective',
    email: 'help@disasterrelief.org',
    phone: '9123456791',
    role: 'ngo',
    city: 'Bangalore',
    state: 'Karnataka',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=disaster',
    createdAt: new Date('2023-05-10'),
    description: 'Rapid response to disaster situations and community resilience building',
    verificationStatus: 'Verified',
    socialHandles: {
      twitter: '@disasterrelief',
      facebook: 'disasterreliefcollective',
    },
    domains: ['Disaster Relief', 'Environmental'],
    volunteersManaged: 45,
    tasksCreated: 31,
  },
  {
    id: 'ngo4',
    name: 'Clean India Mission',
    organizationName: 'Clean India Mission Trust',
    email: 'info@cleanindia.org',
    phone: '9123456792',
    role: 'ngo',
    city: 'Chennai',
    state: 'Tamil Nadu',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=clean',
    createdAt: new Date('2023-08-20'),
    description: 'Working towards sanitation and environmental cleanliness',
    verificationStatus: 'Verified',
    socialHandles: {
      twitter: '@cleanindia',
      instagram: 'cleanindia_mission',
    },
    domains: ['Sanitation', 'Environmental'],
    volunteersManaged: 28,
    tasksCreated: 16,
  },
];

// Mock Community Needs
export const mockCommunityNeeds: CommunityNeed[] = [
  {
    id: 'need1',
    title: 'Medical Camp Required in Slum Area',
    description: 'Free health checkups and medical assistance needed for residents in XYZ slum area. Expected footfall: 200+ people',
    category: 'Medical',
    urgency: 'High',
    status: 'Open',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      latitude: 19.076,
      longitude: 72.8479,
      address: 'Dharavi Slum, Mumbai',
    },
    source: 'Citizen Report',
    reports: 5,
    relatedTasks: ['task1'],
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'need2',
    title: 'School Renovation Needed',
    description: 'Government school in rural area needs infrastructure improvement and repairs. Classrooms need maintenance.',
    category: 'Education',
    urgency: 'Medium',
    status: 'In Progress',
    location: {
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110015',
      latitude: 28.5355,
      longitude: 77.2707,
      address: 'Rural School, Haryana Border',
    },
    source: 'NGO Input',
    reports: 3,
    adoptedByNGO: 'ngo2',
    relatedTasks: ['task2'],
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'need3',
    title: 'Flood Relief Supplies Urgently Needed',
    description: 'Heavy rainfall has displaced 500+ families. Immediate need for food, water, and sanitation kits.',
    category: 'Disaster Relief',
    urgency: 'Critical',
    status: 'Urgent',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560034',
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Bangalore Suburb, near Bellandur Lake',
    },
    source: 'Government Data',
    reports: 12,
    adoptedByNGO: 'ngo3',
    relatedTasks: ['task3', 'task4'],
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'need4',
    title: 'Water Purification System Installation',
    description: 'Village affected by contaminated water supply. Installation of water filtration system required.',
    category: 'Sanitation',
    urgency: 'High',
    status: 'Open',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600026',
      latitude: 13.0827,
      longitude: 80.2707,
      address: 'Village near Chennai',
    },
    source: 'Social Media',
    reports: 7,
    relatedTasks: ['task5'],
    createdAt: new Date('2024-03-18'),
  },
  {
    id: 'need5',
    title: 'Food Security Program for Low-Income Families',
    description: 'Nutrition support and food distribution program needed for 300 families in urban slums.',
    category: 'Food',
    urgency: 'Medium',
    status: 'In Progress',
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: 18.5204,
      longitude: 73.8567,
      address: 'Slum Area, Pune Central',
    },
    source: 'NGO Input',
    reports: 4,
    adoptedByNGO: 'ngo1',
    relatedTasks: ['task6'],
    createdAt: new Date('2024-03-12'),
  },
];

// Mock Volunteer Tasks
export const mockVolunteerTasks: VolunteerTask[] = [
  {
    id: 'task1',
    ngoId: 'ngo1',
    ngoName: 'Health First Foundation',
    title: 'Medical Camp at Dharavi',
    description: 'Organize and conduct a free medical camp providing health checkups, medicine distribution, and health awareness sessions.',
    category: 'Medical',
    requiredSkills: ['Medical Training', 'First Aid', 'Community Health'],
    volunteersNeeded: 8,
    volunteersAccepted: 3,
    acceptedVolunteers: [mockVolunteers[0]],
    applicants: [
      {
        id: 'app1',
        taskId: 'task1',
        volunteerId: 'v1',
        volunteerName: 'Priya Sharma',
        status: 'Accepted',
        appliedAt: new Date('2024-03-16'),
        respondedAt: new Date('2024-03-17'),
        matchScore: 92,
        volunteerSkills: ['Medical Training', 'First Aid'],
        volunteerAvailability: 'Weekends',
      },
      {
        id: 'app2',
        taskId: 'task1',
        volunteerId: 'v2',
        volunteerName: 'Raj Kumar',
        status: 'Applied',
        appliedAt: new Date('2024-03-17'),
        matchScore: 45,
        volunteerSkills: ['Education', 'Tutoring'],
        volunteerAvailability: 'Evenings',
      },
    ],
    deadline: new Date('2024-04-15'),
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      latitude: 19.076,
      longitude: 72.8479,
      address: 'Dharavi Slum, Mumbai',
    },
    urgency: 'High',
    status: 'Open',
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'task2',
    ngoId: 'ngo2',
    ngoName: 'Education for All',
    title: 'School Infrastructure Assessment & Planning',
    description: 'Assess current infrastructure of rural school and plan renovation strategy with community input.',
    category: 'Education',
    requiredSkills: ['Infrastructure Planning', 'Community Outreach', 'Documentation'],
    volunteersNeeded: 5,
    volunteersAccepted: 2,
    acceptedVolunteers: [mockVolunteers[1]],
    applicants: [
      {
        id: 'app3',
        taskId: 'task2',
        volunteerId: 'v2',
        volunteerName: 'Raj Kumar',
        status: 'Accepted',
        appliedAt: new Date('2024-03-11'),
        respondedAt: new Date('2024-03-12'),
        matchScore: 88,
        volunteerSkills: ['Education', 'Tutoring'],
        volunteerAvailability: 'Evenings',
      },
    ],
    deadline: new Date('2024-04-30'),
    location: {
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110015',
      latitude: 28.5355,
      longitude: 77.2707,
      address: 'Rural School, Haryana Border',
    },
    urgency: 'Medium',
    status: 'Open',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'task3',
    ngoId: 'ngo3',
    ngoName: 'Disaster Relief Collective',
    title: 'Flood Relief Food Distribution',
    description: 'Distribute food packets and emergency supplies to displaced families affected by recent flooding.',
    category: 'Disaster Relief',
    requiredSkills: ['Disaster Management', 'Logistics', 'Physical Fitness'],
    volunteersNeeded: 15,
    volunteersAccepted: 6,
    acceptedVolunteers: [mockVolunteers[2], mockVolunteers[3]],
    applicants: [
      {
        id: 'app4',
        taskId: 'task3',
        volunteerId: 'v3',
        volunteerName: 'Ananya Desai',
        status: 'Accepted',
        appliedAt: new Date('2024-03-20'),
        respondedAt: new Date('2024-03-20'),
        matchScore: 95,
        volunteerSkills: ['Disaster Management', 'Logistics'],
        volunteerAvailability: 'Full-time',
      },
      {
        id: 'app5',
        taskId: 'task3',
        volunteerId: 'v4',
        volunteerName: 'Vikram Singh',
        status: 'Accepted',
        appliedAt: new Date('2024-03-20'),
        respondedAt: new Date('2024-03-20'),
        matchScore: 90,
        volunteerSkills: ['Food Distribution', 'Cooking'],
        volunteerAvailability: 'Weekdays',
      },
    ],
    deadline: new Date('2024-03-25'),
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560034',
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Bangalore Suburb, near Bellandur Lake',
    },
    urgency: 'Critical',
    status: 'Open',
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'task4',
    ngoId: 'ngo3',
    ngoName: 'Disaster Relief Collective',
    title: 'Emergency Shelter Setup',
    description: 'Set up temporary shelters and ensure sanitation facilities for displaced families.',
    category: 'Disaster Relief',
    requiredSkills: ['Construction', 'Sanitation', 'Physical Fitness'],
    volunteersNeeded: 12,
    volunteersAccepted: 4,
    acceptedVolunteers: [mockVolunteers[2]],
    applicants: [
      {
        id: 'app6',
        taskId: 'task4',
        volunteerId: 'v3',
        volunteerName: 'Ananya Desai',
        status: 'Accepted',
        appliedAt: new Date('2024-03-20'),
        respondedAt: new Date('2024-03-20'),
        matchScore: 93,
        volunteerSkills: ['Disaster Management', 'Logistics'],
        volunteerAvailability: 'Full-time',
      },
    ],
    deadline: new Date('2024-03-24'),
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560034',
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Bangalore Suburb, near Bellandur Lake',
    },
    urgency: 'Critical',
    status: 'Open',
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'task5',
    ngoId: 'ngo4',
    ngoName: 'Clean India Mission',
    title: 'Water Filtration System Installation',
    description: 'Install water purification systems and conduct community training on water safety and maintenance.',
    category: 'Sanitation',
    requiredSkills: ['Water Conservation', 'Technical Skills', 'Community Training'],
    volunteersNeeded: 6,
    volunteersAccepted: 1,
    acceptedVolunteers: [mockVolunteers[4]],
    applicants: [
      {
        id: 'app7',
        taskId: 'task5',
        volunteerId: 'v5',
        volunteerName: 'Meera Patel',
        status: 'Accepted',
        appliedAt: new Date('2024-03-18'),
        respondedAt: new Date('2024-03-18'),
        matchScore: 85,
        volunteerSkills: ['Environmental Conservation', 'Water Conservation'],
        volunteerAvailability: 'Flexible',
      },
    ],
    deadline: new Date('2024-04-10'),
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600026',
      latitude: 13.0827,
      longitude: 80.2707,
      address: 'Village near Chennai',
    },
    urgency: 'High',
    status: 'Open',
    createdAt: new Date('2024-03-18'),
  },
  {
    id: 'task6',
    ngoId: 'ngo1',
    ngoName: 'Health First Foundation',
    title: 'Nutrition Support Program Coordination',
    description: 'Coordinate food distribution and nutrition counseling for low-income families in urban slums.',
    category: 'Food',
    requiredSkills: ['Nutrition Knowledge', 'Community Outreach', 'Logistics'],
    volunteersNeeded: 8,
    volunteersAccepted: 2,
    acceptedVolunteers: [mockVolunteers[3]],
    applicants: [
      {
        id: 'app8',
        taskId: 'task6',
        volunteerId: 'v4',
        volunteerName: 'Vikram Singh',
        status: 'Accepted',
        appliedAt: new Date('2024-03-12'),
        respondedAt: new Date('2024-03-13'),
        matchScore: 88,
        volunteerSkills: ['Food Distribution', 'Cooking'],
        volunteerAvailability: 'Weekdays',
      },
    ],
    deadline: new Date('2024-05-15'),
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      latitude: 18.5204,
      longitude: 73.8567,
      address: 'Slum Area, Pune Central',
    },
    urgency: 'Medium',
    status: 'Open',
    createdAt: new Date('2024-03-12'),
  },
];

// Mock Normal Users
export const mockNormalUsers: NormalUser[] = [
  {
    id: 'u1',
    name: 'Amit Verma',
    email: 'amit@example.com',
    phone: '9876543215',
    role: 'user',
    city: 'Mumbai',
    state: 'Maharashtra',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amit',
    createdAt: new Date('2024-01-20'),
    reportedNeeds: 3,
  },
  {
    id: 'u2',
    name: 'Sangeeta Desai',
    email: 'sangeeta@example.com',
    phone: '9876543216',
    role: 'user',
    city: 'Delhi',
    state: 'Delhi',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sangeeta',
    createdAt: new Date('2024-02-01'),
    reportedNeeds: 2,
  },
];

export const mockCategories = [
  'Food',
  'Medical',
  'Education',
  'Sanitation',
  'Disaster Relief',
  'Infrastructure',
  'Environmental',
  'Social Support',
];

export const mockSkills = [
  'Medical Training',
  'First Aid',
  'Community Health',
  'Education',
  'Tutoring',
  'Programming',
  'Disaster Management',
  'Logistics',
  'Community Outreach',
  'Food Distribution',
  'Cooking',
  'Sanitation',
  'Food Safety',
  'Environmental Conservation',
  'Waste Management',
  'Water Conservation',
  'Construction',
  'Teaching Certification',
  'Hygiene Certification',
  'Environmental Science',
];

// Mock Task Applications
export const mockTaskApplications: VolunteerApplication[] = [
  {
    id: 'app-1',
    taskId: 'task1',
    volunteerId: 'v1',
    volunteerName: 'Priya Sharma',
    status: 'Applied',
    appliedAt: new Date('2024-03-18'),
    matchScore: 85,
    volunteerSkills: ['Medical Training', 'First Aid', 'Community Health'],
    volunteerAvailability: 'Weekends',
  },
  {
    id: 'app-2',
    taskId: 'task2',
    volunteerId: 'v2',
    volunteerName: 'Raj Kumar',
    status: 'Accepted',
    appliedAt: new Date('2024-03-15'),
    respondedAt: new Date('2024-03-16'),
    matchScore: 78,
    volunteerSkills: ['Education', 'Tutoring', 'Programming'],
    volunteerAvailability: 'Evenings',
  },
  {
    id: 'app-3',
    taskId: 'task3',
    volunteerId: 'v3',
    volunteerName: 'Ananya Desai',
    status: 'Applied',
    appliedAt: new Date('2024-03-20'),
    matchScore: 92,
    volunteerSkills: ['Disaster Management', 'Logistics', 'Community Outreach'],
    volunteerAvailability: 'Full-time',
  },
  {
    id: 'app-4',
    taskId: 'task1',
    volunteerId: 'v4',
    volunteerName: 'Vikram Singh',
    status: 'Rejected',
    appliedAt: new Date('2024-03-17'),
    respondedAt: new Date('2024-03-18'),
    matchScore: 45,
    volunteerSkills: ['Food Distribution', 'Cooking'],
    volunteerAvailability: 'Weekdays',
  },
];
